### PR TITLE
remove remaining message content features

### PR DESCRIPTION
**Pull request by hkubus**
removes antibot and ai (also removes messageCreate since it isnt needed anymore really)

### CODE REVIEW

**Review by Nyameliaaaa — APPROVED** [review]
ok so be aware i might research into a better antibot also didnt we want to add an anti toxicity thing

**Review by Nyameliaaaa — CHANGES_REQUESTED** [review]
i redact my approval.
can you please bring back the "hi! type / to view my commands" message when bot is mentioned?

**Comment by hkubus** [comment]
no

**Review by SuperchupuDev — APPROVED** [review]

**Review by Nyameliaaaa — APPROVED** [review]
[redacted]

**Pull request merged**
