### PR TITLE
commas

### PR DESCRIPTION
**Pull request by ArsBeneMoriendi**

### CODE REVIEW

**Comment by Nyameliaaaa** [comment]
sorry but this string isnt used anymore

@SuperchupuDev can you go ahead and remove the remaining perm strings

**Comment by SuperchupuDev** [comment]
@night-lake the strings are actually used since subcommands can't use perms v2, maybe in the next minor version we can move them to a `shop-config` command?

**Review by SuperchupuDev — APPROVED** [review]

**Comment by Nyameliaaaa** [comment]
> @night-lake the strings are actually used since subcommands can't use perms v2, maybe in the next minor version we can move them to a `shop-config` command?

maybe yeah but we could call it /shop-admin or something

**Review by Nyameliaaaa — APPROVED** [review]
idk polish so if someone bullies us for this we'll change it back

**Comment by SuperchupuDev** [comment]
@night-lake weren't you going to make commits to this pr

**Comment by Nyameliaaaa** [comment]
> @night-lake weren't you going to make commits to this pr

ill do that tmrw

**Comment by hkubus** [comment]
fake

śr., 18 maj 2022 o 12:21 sadie katherine ***@***.***>
napisał(a):

**Pull request merged**
