### PR TITLE
dashboard backend

### PR DESCRIPTION
**Pull request by hkubus**

### CODE REVIEW

**Comment by hkubus** [comment]
GET /guilds/ - returns the guilds that the user is in (id, name, and whether fluorine is in it)
GET /guild/:id - returns basic data about the guild
GET /guild/:id/economy - returns economy stats (leaderboards and other stuff)
GET /guild/:id/tickets - ticket data 
GET /guild/:id/cases -  get data about cases
PATCH /guild/:id - change settings
PATCH /guild/:id/case/:caseid - change a reason of a case
PATCH /guild/:id/economy/:userid - change someone's moners
DELETE /guild/:id/case/:caseid - delete a case

**Review by Nyameliaaaa — DISMISSED** [review]
i think itd be better if you didnt import every route manually

**Comment by hkubus** [comment]
> i think itd be better if you didnt import every route manually

we (me andsuperchup) wanted to do that but there was no lib that did that in a cool way

**Review by SuperchupuDev — APPROVED** [review]
i really havent tested the code myself but it looks overall good, can you move the `#classes` imports above the dependency imports in [`api/guilds/[id]/cases/index.ts`](https://github.com/Fluorinebot/fluorine/pull/328/files#diff-e04cb18869ce4851e934b2410394b876d242af3c02b2eef3c146c15042989f7c), [`api/guilds/[id]/channels.ts`](https://github.com/Fluorinebot/fluorine/pull/328/files#diff-2dc538668a72594a4c9ecdb460c162d94867aee283f8399293f32be530458c60), [`api/guilds/[id]/economy/[userId].ts`](https://github.com/Fluorinebot/fluorine/pull/328/files#diff-54d4142fec7c88f2166c5dbf178696c1d2a0a0665b0932cdc1cf653366a14512), [`api/guilds/[id]/economy/index.ts`](https://github.com/Fluorinebot/fluorine/pull/328/files#diff-e2be888b79db901e2895da7e88e43b0bf6682d31e3c4dbb2f21f13b5cc382c1d), [`api/guilds/[id]/roles.ts`](https://github.com/Fluorinebot/fluorine/pull/328/files#diff-21b7ce7e59ba5b63dc1e1475efa00617e9f42fbeb7e35b00efeb7b3bf5d619bd), [`api/guilds/[id]/users/[id].ts`](https://github.com/Fluorinebot/fluorine/pull/328/files#diff-31b0bf849b6d615bc46a2b1f38dcfcce1e5397c34dd152dbd88f04445902c0a1) and [`api/tokenCheck.ts`](https://github.com/Fluorinebot/fluorine/pull/328/files#diff-e129adfe3364a26ba8912b0ce82d4dfea07cb02a1eaa4a85c4151bb6a36f33da)? sorry for taking this long :^)

**Pull request merged**
