### PR TITLE
localized components

### PR DESCRIPTION
**Pull request by Nyameliaaaa**
this pr adds a set of builders that automatically localize components, as well as improve the localized embed builder

### CODE REVIEW

**Comment by hkubus** [comment]
brrrrrrrrrrrrrrrro

**Comment by Nyameliaaaa** [comment]
> brrrrrrrrrrrrrrrro

@SuperchupuDev please review

kubus depends on it

**Comment by SuperchupuDev** [comment]
ci is failing

**Comment by Nyameliaaaa** [comment]
@SuperchupuDev ci should be fixed

**Review by SuperchupuDev — APPROVED** [review]
the amount of work you put into this leaves me with no words, you managed to implement systems that no one else was able to get working, amazing job

**Pull request merged**
