### PR TITLE
dynamic events and handlers

### PR DESCRIPTION
**Pull request by hkubus**

### CODE REVIEW

**Comment by Nyameliaaaa** [comment]
@SuperchupuDev can you make interactionCreate use the new module system?

**Comment by SuperchupuDev** [comment]
> @SuperchupuDev can you make interactionCreate use the new module system?

sure

**Review by Nyameliaaaa — DISMISSED** [review]
sex

(will be reloadble funnies)

**Review by Nyameliaaaa — APPROVED** [review]
i hate json

**Pull request closed without merging**
