### PR TITLE
use i18next

### LINKED ISSUE #77: i18next
- [x] patch one lang only commands
    - [x] get kubus to do kurwa
- [x] json restructure
- [x] retype
- [x] i18next hour

### PR DESCRIPTION
**Pull request by SuperchupuDev**
closes #77

### CODE REVIEW

**Review by Nyameliaaaa — DISMISSED** [review]
this is torture

**Comment by Nyameliaaaa** [comment]
nvm some of these have `lang` instead of lng

**Comment by SuperchupuDev** [comment]
> nvm some of these have `lang` instead of lng

whoops thanks for noticing

**Review by Nyameliaaaa — APPROVED** [review]
yeah

**Review by hkubus — APPROVED** [review]

**Pull request merged**
